-- 기안 종류 테이블 --
CREATE TABLE TBL_DRAFT_TYPE
(DRAFT_TYPE_NO NUMBER -- 기안 종류 번호(기본키)
,DRAFT_TYPE NVARCHAR2(10) NOT NULL -- 기안 종류 이름
,constraint PK_TBL_DRAFT_TYPE_DRAFT_TYPE_NO primary key(DRAFT_TYPE_NO)
);

INSERT INTO TBL_DRAFT_TYPE VALUES(1, '업무품의');
INSERT INTO TBL_DRAFT_TYPE VALUES(2, '지출결의서');
INSERT INTO TBL_DRAFT_TYPE VALUES(3, '출장보고서');
COMMIT;

-- 기안 문서 테이블 --
CREATE TABLE TBL_DRAFT
(DRAFT_NO NUMBER -- 문서번호(기본키)
,FK_DRAFT_TYPE_NO NOT NULL -- 기안 종류 번호(외래키)
,FK_DRAFT_EMPNO NOT NULL -- 기안자 사원번호(외래키)
,DRAFT_SUBJECT NVARCHAR2(100) NOT NULL -- 문서 제목
,DRAFT_CONTENT CLOB NOT NULL -- 문서 내용
,DRAFT_COMMENT NVARCHAR2(400) -- 기안 의견
,DRAFT_DATE DATE DEFAULT SYSDATE NOT NULL -- 작성일자
,ORG_FILENAME VARCHAR2(50) -- 원본 파일명
,FILENAME VARCHAR2(50) -- 저장된 파일명
,FILESIZE NUMBER -- 파일크기
,TEMP NUMBER(1) DEFAULT 0 -- 임시저장 여부 (0: 임시저장아님, 1:임시저장)
,CONSTRAINT PK_TBL_DRAFT_DRAFT_NO PRIMARY KEY(DRAFT_NO)
,CONSTRAINT FK_TBL_DRAFT_FK_DRAFT_TYPE_NO FOREIGN KEY(FK_DRAFT_TYPE_NO) REFERENCES TBL_DRAFT_TYPE(DRAFT_TYPE_NO)
,CONSTRAINT FK_TBL_DRAFT_FK_DRAFT_EMPNO FOREIGN KEY(FK_DRAFT_EMPNO) REFERENCES TBL_EMPLOYEE(EMPNO)
,CONSTRAINT CK_TBL_DRAFT_TEMP CHECK( TEMP IN (0,1))
);

-- 기안문서 번호 시퀀스 --
CREATE SEQUENCE SEQ_DRAFT_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE;

INSERT INTO TBL_DRAFT
(DRAFT_NO, FK_DRAFT_TYPE_NO, FK_DRAFT_EMPNO, DRAFT_SUBJECT, DRAFT_CONTENT)
VALUES(SEQ_DRAFT_NO.NEXTVAL, 1, 5, '결재올립니다', '결재해주십시오');
COMMIT;

-- 기안 결재 테이블 --
CREATE TABLE TBL_APPROVAL
(APPROVAL_NO NUMBER -- 결재 일련번호(기본키)
,FK_DRAFT_NO NUMBER NOT NULL -- 문서번호(외래키)
,FK_APPROVAL_EMPNO NOT NULL -- 결재할 사원번호(외래키)
,LEVELNO NUMBER NOT NULL -- 결재 단계
,APPROVAL_STATUS NUMBER(1) DEFAULT 0 NOT NULL -- 결재 상태 (0:미결, 1:결재, 2:반려, -1: 처리불가(아래에서 반려함))
,APPROVAL_COMMENT NVARCHAR2(200) -- 결재 의견
,APPROVAL_DATE DATE -- 결재 일자
,CONSTRAINT PK_TBL_APPROVAL_APPROVAL_NO  PRIMARY KEY(APPROVAL_NO)
,CONSTRAINT FK_TBL_APPROVAL_FK_DRAFT_NO FOREIGN KEY(FK_DRAFT_NO) REFERENCES TBL_DRAFT(DRAFT_NO)
,CONSTRAINT FK_TBL_APPROVAL_FK_APPROVAL_EMPNO FOREIGN KEY(FK_APPROVAL_EMPNO) REFERENCES TBL_EMPLOYEE(EMPNO)
,CONSTRAINT CK_TBL_APPROVAL_APPROVAL_STATUS CHECK( APPROVAL_STATUS IN (0,1,2,-1))
);

-- 기안 결재 번호 시퀀스 --
CREATE SEQUENCE SEQ_APPROVAL_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE;

INSERT INTO TBL_APPROVAL
(APPROVAL_NO, FK_DRAFT_NO, FK_APPROVAL_EMPNO, LEVELNO)
VALUES(SEQ_APPROVAL_NO.NEXTVAL, 1, 3, 2);

INSERT INTO TBL_APPROVAL
(APPROVAL_NO, FK_DRAFT_NO, FK_APPROVAL_EMPNO, LEVELNO)
VALUES(SEQ_APPROVAL_NO.NEXTVAL, 1, 2, 3);
COMMIT;

-- 지출 내역 테이블 --
CREATE TABLE TBL_EXPENSE_LIST
(EXPENSE_LIST_NO NUMBER -- 지출 내역번호(기본키)
,FK_DRAFT_NO NOT NULL -- 기안 문서 번호(외래키)
,EXPENSE_DATE DATE DEFAULT SYSDATE NOT NULL -- 지출일자
,EXPENSE_TYPE NVARCHAR2(10) NOT NULL -- 지출분류
,EXPENSE_DETAIL NVARCHAR2(50) NOT NULL -- 지출내역
,EXPENSE_AMOUNT NUMBER NOT NULL -- 금액
,EXPENSE_REMARK NVARCHAR2(100) -- 비고
,CONSTRAINT PK_TBL_EXPENSE_LIST_EXPENSE_LIST_NO PRIMARY KEY(EXPENSE_LIST_NO)
,CONSTRAINT FK_TBL_EXPENSE_LIST_FK_DRAFT_NO FOREIGN KEY(FK_DRAFT_NO) REFERENCES TBL_DRAFT(DRAFT_NO)
);

-- 출장 보고 테이블 --
CREATE TABLE TBL_BIZ_TRIP_REP
(BIZ_TRIP_REP_NO NUMBER -- 출장 보고 번호(기본키)
,FK_DRAFT_NO NOT NULL -- 기안 문서 번호(외래키)
,TRIP_PURPOSE NVARCHAR2(300) NOT NULL -- 출장 목적
,TRIP_START_DATE DATE NOT NULL -- 출장 시작일
,TRIP_END_DATE DATE NOT NULL -- 출장 종료일
,TRIP_LOCATION NVARCHAR2(200) -- 출장 지역
,CONSTRAINT PK_TBL_BIZ_TRIP_REP_BIZ_TRIP_REP_NO PRIMARY KEY(BIZ_TRIP_REP_NO)
,CONSTRAINT FK_TBL_BIZ_TRIP_REP_FK_DRAFT_NO FOREIGN KEY(FK_DRAFT_NO) REFERENCES TBL_DRAFT(DRAFT_NO)
);

-- 저장된 결재라인 테이블 --
CREATE TABLE TBL_MY_APRV_LINE
(APRV_LINE_NO NUMBER -- 결재라인 번호(기본키)
,APRV_LINE_NAME NVARCHAR2(50) NOT NULL -- 결재라인 이름
,FK_EMPNO NOT NULL -- 결재라인 소유자 사원번호(외래키)
,FK_APPROVAL_EMPNO1 NOT NULL -- 첫번째 결재자 사원번호(외래키)
,FK_APPROVAL_EMPNO2 NOT NULL -- 두번째 결재자 사원번호(외래키)
,FK_APPROVAL_EMPNO3 NOT NULL -- 세번째 결재자 사원번호(외래키)
,CONSTRAINT PK_TBL_MY_APRV_LINE_APRV_LINE_NO PRIMARY KEY(APRV_LINE_NO)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_EMPNO FOREIGN KEY(FK_EMPNO) REFERENCES TBL_EMPLOYEE(EMPNO)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_APPROVAL_EMPNO1 FOREIGN KEY(FK_APPROVAL_EMPNO1) REFERENCES TBL_EMPLOYEE(EMPNO)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_APPROVAL_EMPNO2 FOREIGN KEY(FK_APPROVAL_EMPNO2) REFERENCES TBL_EMPLOYEE(EMPNO)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_APPROVAL_EMPNO3 FOREIGN KEY(FK_APPROVAL_EMPNO3) REFERENCES TBL_EMPLOYEE(EMPNO)
);

-- 명언 테이블 --
CREATE TABLE TBL_TODAY_PROVERB
(PROVERB_NO NUMBER -- 명언번호(기본키)
,PROVERB NVARCHAR2(500) NOT NULL -- 명언
,CONSTRAINT PK_TBL_TODAY_PROVERB_PROVERB_NO PRIMARY KEY(PROVERB_NO)
);

--------------------------------------------------------------------------------

-- 결재정보를 join하여 가져오는 뷰 --
create or replace view view_draft_approval
as
SELECT case when DRAFT_status = 0 then null else APPROVAL_DATE end as APPROVAL_DATE, 
DRAFT_DATE, draft_type, draft_no, FK_DRAFT_EMPNO, urgent_status, FK_APPROVAL_EMPNO,
name as DRAFT_EMP_NAME, DRAFT_SUBJECT, DRAFT_status, department as draft_DEPARTMENT
FROM TBL_APPROVAL JOIN TBL_DRAFT
ON FK_DRAFT_NO = DRAFT_NO
JOIN TBL_EMPLOYEE
ON EMPNO = FK_DRAFT_EMPNO;




-- 팀 결재함 문서 전체 목록 뷰 --
create or replace view view_team_draft
as
select case when DRAFT_status = 0 then null else APPROVAL_DATE end as APPROVAL_DATE, 
DRAFT_DATE, draft_type, draft_no, FK_DRAFT_EMPNO, urgent_status,
name as DRAFT_EMP_NAME, DRAFT_SUBJECT, DRAFT_status, department as draft_DEPARTMENT
FROM
(select DRAFT_DATE, draft_type, draft_no, FK_DRAFT_EMPNO, DRAFT_SUBJECT, DRAFT_status, APPROVAL_DATE, urgent_status
from tbl_draft join 
(select max(APPROVAL_DATE) as APPROVAL_DATE, fk_draft_no from tbl_approval group by fk_draft_no)
on draft_no = fk_draft_no
where DRAFT_status != 0 and temp = 0) join
tbl_employee
on empno = fk_draft_empno
;

-- 개인문서함 상신함 목록 뷰 --
create or replace view view_draft_sent
as
select case when DRAFT_status = 0 then null else APPROVAL_DATE end as APPROVAL_DATE, DRAFT_DATE, draft_type, draft_no,
FK_DRAFT_EMPNO, NAME as DRAFT_EMP_NAME, DRAFT_SUBJECT, DRAFT_status, urgent_status
from tbl_draft join
(select max(APPROVAL_DATE) as APPROVAL_DATE, fk_draft_no from tbl_approval group by fk_draft_no)
on draft_no = fk_draft_no
and temp = 0 join
tbl_employee
on empno = fk_draft_empno
;

-- 개인문서함 결재함 목록 뷰 --
create or replace view view_my_draft_processed
as
SELECT case when DRAFT_status = 0 then null else APPROVAL_DATE end as APPROVAL_DATE, DRAFT_DATE, DRAFT_TYPE, DRAFT_NO,
FK_DRAFT_EMPNO, NAME as DRAFT_EMP_NAME, fk_approval_empno, DRAFT_SUBJECT,department as draft_DEPARTMENT, urgent_status, DRAFT_status
FROM TBL_DRAFT JOIN (select APPROVAL_DATE, approval_STATUS, fk_approval_empno, fk_draft_no from tbl_approval)
ON DRAFT_NO = FK_DRAFT_NO
and approval_STATUS IN (1,2) join
tbl_employee
on empno = fk_draft_empno
;

-- 결재 대기문서 목록 select문 --
SELECT DISTINCT DRAFT_DATE, DRAFT_TYPE, DRAFT_NO, FK_DRAFT_EMPNO, 
NAME AS DRAFT_EMP_NAME, DRAFT_SUBJECT, URGENT_STATUS
FROM TBL_DRAFT JOIN TBL_APPROVAL
ON DRAFT_NO = FK_DRAFT_NO
AND DRAFT_NO IN (
    SELECT FK_DRAFT_NO
    FROM TBL_APPROVAL A
    WHERE FK_APPROVAL_EMPNO = 2 AND APPROVAL_STATUS = 0
    AND FK_DRAFT_NO IN (SELECT FK_DRAFT_NO
                        FROM TBL_APPROVAL
                        WHERE LEVELNO = (A.LEVELNO - 1) AND APPROVAL_STATUS = 1)
    )
JOIN TBL_EMPLOYEE
ON EMPNO = FK_DRAFT_EMPNO
;

-- fk_draft_no = 1, 4
-- levelno = 3

select fk_draft_no
from tbl_approval
where levelno = (levelno - 1) and approval_status = 1

--------------------------------------------------------------------------------
