-- 기안 종류 테이블 --
CREATE TABLE TBL_DRAFT_TYPE
(DRAFT_TYPE_NO NUMBER -- 기안 종류 번호(기본키)
,DRAFT_TYPE NVARCHAR2(10) NOT NULL -- 기안 종류 이름
,constraint PK_TBL_DRAFT_TYPE_DRAFT_TYPE_NO primary key(DRAFT_TYPE_NO)
);

--------------------------------------------------------------------------------

-- 기안 문서 테이블 --
CREATE TABLE TBL_DRAFT
(DRAFT_NO NUMBER -- 문서번호(기본키)
,FK_DRAFT_TYPE_NO NOT NULL -- 기안 종류 번호(외래키)
,FK_DRAFT_EMPLOYEE_ID NOT NULL -- 기안자 사원번호(외래키)
,DRAFT_SUBJECT NVARCHAR2(100) NOT NULL -- 문서 제목
,DRAFT_CONTENT CLOB NOT NULL -- 문서 내용
,DRAFT_DATE DATE DEFAULT SYSDATE NOT NULL -- 작성일자
,ORG_FILENAME VARCHAR2(50) -- 원본 파일명
,FILENAME VARCHAR2(50) -- 저장된 파일명
,FILESIZE NUMBER -- 파일크기
,TEMP NUMBER(1) DEFAULT 0 -- 임시저장 여부 (0: 임시저장아님, 1:임시저장)
,CONSTRAINT PK_TBL_DRAFT_DRAFT_NO PRIMARY KEY(DRAFT_NO)
,CONSTRAINT FK_TBL_DRAFT_FK_DRAFT_TYPE_NO FOREIGN KEY(FK_DRAFT_TYPE_NO) REFERENCES TBL_DRAFT_TYPE(DRAFT_TYPE_NO)
,CONSTRAINT FK_TBL_DRAFT_FK_DRAFT_EMPLOYEE_ID FOREIGN KEY(FK_DRAFT_EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID)
,CONSTRAINT CK_TBL_DRAFT_TEMP CHECK( TEMP IN (0,1))
);

-- 기안 결재 테이블 --
CREATE TABLE TBL_APPROVAL
(APPROVAL_NO NUMBER -- 결재 일련번호(기본키)
,FK_DRAFT_NO NUMBER NOT NULL -- 문서번호(외래키)
,FK_APPROVAL_EMPLOYEE_ID NOT NULL -- 결재할 사원번호(외래키)
,LEVELNO NUMBER NOT NULL -- 결재 단계
,APPROVAL_STATUS NUMBER(1) DEFAULT 0 NOT NULL -- 결재 상태 (0:미결, 1:결재, 2:반려, -1: 처리불가(아래에서 반려함))
,APPROVAL_COMMENT NVARCHAR2(200) -- 결재 의견
,APPROVAL_DATE DATE -- 결재 일자
,CONSTRAINT PK_TBL_APPROVAL_APPROVAL_NO  PRIMARY KEY(APPROVAL_NO)
,CONSTRAINT FK_TBL_APPROVAL_FK_DRAFT_NO FOREIGN KEY(FK_DRAFT_NO) REFERENCES TBL_DRAFT(DRAFT_NO)
,CONSTRAINT FK_TBL_APPROVAL_FK_APPROVAL_EMPLOYEE_ID FOREIGN KEY(FK_APPROVAL_EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID)
,CONSTRAINT CK_TBL_APPROVAL_APPROVAL_STATUS CHECK( APPROVAL_STATUS IN (0,1,2,-1))
);

-- 지출 내역 테이블 --
CREATE TABLE TBL_EXPENSE_LIST
(EXPENSE_LIST_NO NUMBER -- 지출 내역번호(기본키)
,FK_DRAFT_NO NOT NULL -- 기안 문서 번호(외래키)
,EXPENSE_DATE DATE DEFAULT SYSDATE NOT NULL -- 지출일자
,EXPENSE_TYPE NVARCHAR2(10) NOT NULL -- 지출분류
,EXPENSE_DETAIL NVARCHAR2(50) NOT NULL -- 지출내역
,EXPENSE_AMOUNT NUMBER NOT NULL -- 금액
,EXPENSE_REMARK NVARCHAR2(100) -- 비고
,CONSTRAINT PK_TBL_EXPENSE_LIST_EXPENSE_LIST_NO PRIMARY KEY(EXPENSE_LIST_NO)
,CONSTRAINT FK_TBL_EXPENSE_LIST_FK_DRAFT_NO FOREIGN KEY(FK_DRAFT_NO) REFERENCES TBL_DRAFT(DRAFT_NO)
);

-- 출장 보고 테이블 --
CREATE TABLE TBL_BIZ_TRIP_REP
(BIZ_TRIP_REP_NO NUMBER -- 출장 보고 번호(기본키)
,FK_DRAFT_NO NOT NULL -- 기안 문서 번호(외래키)
,TRIP_PURPOSE NVARCHAR2(300) NOT NULL -- 출장 목적
,TRIP_START_DATE DATE NOT NULL -- 출장 시작일
,TRIP_END_DATE DATE NOT NULL -- 출장 종료일
,TRIP_LOCATION NVARCHAR2(200) -- 출장 지역
,CONSTRAINT PK_TBL_BIZ_TRIP_REP_BIZ_TRIP_REP_NO PRIMARY KEY(BIZ_TRIP_REP_NO)
,CONSTRAINT FK_TBL_BIZ_TRIP_REP_FK_DRAFT_NO FOREIGN KEY(FK_DRAFT_NO) REFERENCES TBL_DRAFT(DRAFT_NO)
);

-- 저장된 결재라인 테이블 --
CREATE TABLE TBL_MY_APRV_LINE
(APRV_LINE_NO NUMBER -- 결재라인 번호(기본키)
,APRV_LINE_NAME NVARCHAR2(50) NOT NULL -- 결재라인 이름
,FK_EMPLOYEE_ID NOT NULL -- 결재라인 소유자 사원번호(외래키)
,FK_APPROVAL_EMPLOYEE_ID1 NOT NULL -- 첫번째 결재자 사원번호(외래키)
,FK_APPROVAL_EMPLOYEE_ID2 NOT NULL -- 두번째 결재자 사원번호(외래키)
,FK_APPROVAL_EMPLOYEE_ID3 NOT NULL -- 세번째 결재자 사원번호(외래키)
,CONSTRAINT PK_TBL_MY_APRV_LINE_APRV_LINE_NO PRIMARY KEY(BIZ_TRIP_REP_NO)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_EMPLOYEE_ID FOREIGN KEY(FK_EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_APPROVAL_EMPLOYEE_ID1 FOREIGN KEY(FK_APPROVAL_EMPLOYEE_ID1) REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_APPROVAL_EMPLOYEE_ID2 FOREIGN KEY(FK_APPROVAL_EMPLOYEE_ID2) REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID)
,CONSTRAINT FK_TBL_MY_APRV_LINE_FK_APPROVAL_EMPLOYEE_ID3 FOREIGN KEY(FK_APPROVAL_EMPLOYEE_ID3) REFERENCES TBL_EMPLOYEES(EMPLOYEE_ID)
);

-- 명언 테이블 --
CREATE TABLE TBL_TODAY_PROVERB
(PROVERB_NO NUMBER -- 명언번호(기본키)
,PROVERB NVARCHAR2(500) NOT NULL -- 명언
,CONSTRAINT PK_TBL_TODAY_PROVERB_PROVERB_NO PRIMARY KEY(PROVERB_NO)
);